{
    "name": "AI Ticket Booking",
    "summary": "AI-assisted ticket acquisition orchestration with human intervention and external worker integration",
    "version": "19.0.1.0.9",
    "category": "Operations",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["base", "mail"],
    "data": [
        "security/ai_ticket_security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/cron.xml",
        "views/ticket_request_views.xml",
        "views/ticket_provider_views.xml",
        "views/ticket_traveler_views.xml",
        "views/ticket_release_views.xml",
        "views/ticket_action_views.xml",
        "views/ticket_execution_views.xml",
        "views/ticket_log_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
}
